name: Update spec files
on:
  # Allows for manually running an update from the actions tab
  workflow_dispatch:

  schedule:
    # Runs every day at ~12am UTC
    - cron: '0 0 * * *'

# Revoke all default permissions
permissions: {}

jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    permissions:
      # needed to write updated specs to this repo
      contents: write

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: aidandenlinger/autocopr@v1 # not fixing to a SHA because it's my code :)
        with:
          mode: "push"
